apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-validacao-negocio
  name: api-validacao-negocio
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: api-validacao-negocio
  type: LoadBalancer
status:
  loadBalancer: {}
